### ISSUE TITLE
Apache Flex Installer link broken.

### ISSUE THREAD

**Issue by schwack** [swfobject/swfobject#35]
Just a heads up, the Apache Flex installer (4.13.0) fails with the following error:

Downloading 2.2.zip from: https://github.com/swfobject/swfobject/archive
      [get] [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032" errorID=2032]

**Comment by tensafefrogs** [comment]
Hmm, the release hasn't been removed or changed... could that be a transient error?

The releases page shows that url:
https://github.com/swfobject/swfobject/releases

Which works:
https://github.com/swfobject/swfobject/archive/2.2.zip

**Comment by schwack** [comment]
My apologies, I may have jumped the gun. I naturally assumed that when the installer said it failed 
"Downloading 2.2.zip from: https://github.com/swfobject/swfobject/archive[get] IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032" errorID=2032"
that it was telling me the truth. Following the path to the repo and seeing 
"This GitHub edition of SWFObject is our 2.3 beta. The current release – 2.2 – is still available for download at code.google.com/p/swfobject/"
seemingly validated the problem. 
Apparently the Flex installer is either:a) not picking up the alias from the config file, in which case it may be trying to download from the url for 2.3 and the installer is telling the truth, orb) looking  in the right place, failing to download (??) and reporting the wrong error...
Hmmm...  I can download it np....
wait...   if I download from http://swfobject.googlecode.com/files/swfobject_2_2.zip  I get "swfobject_2_2.zip"from https://github.com/swfobject/swfobject/archive/2.2.zip I get "swfobject-2_2.zip"
That could be a problem.....
Date: Thu, 8 Jan 2015 11:51:06 -0800

**Comment by qbuchanan** [comment]
This appears to be broken again ( May 20, 2015 ) and I will be opening a new issue both here and on the flex sdk installer tracker as well.

**Comment by qbuchanan** [comment]
The current issue appears to be with the MD5 of the downloaded zip file.

**Comment by DCleymans** [comment]
What is the link to the issue on the flex sdk installer tracker?

**Comment by wouter-crowdpark** [comment]
https://issues.apache.org/jira/browse/FLEX-34851

**Comment by qbuchanan** [comment]
The Flex SDK installer has been updated to reflect the new MD5, installation should work now :-)

**Comment by modecolems** [comment]
Hi, still not working for me :
Installer version 3.1.0 downloaded today.

Thx

**Comment by qbuchanan** [comment]
Mory,
which version of the Flex SDK were you trying to install.  I suspect the
new md5 hasn't been updated in all the install xml's

**Comment by modecolems** [comment]
Hi, thx for the fast reply.

Indeed, I'm trying to install the last one 4.14.1

Regards.

**Comment by qbuchanan** [comment]
Mory,
try it again.  When I install it appears to work fine, but there are a lot
of different sdks and combinations, which version of air are you trying to
install?

**Comment by doroshko** [comment]
I'm trying to install Flex 4.14.1 (AIR 3.9)

**Comment by qbuchanan** [comment]
Mory,
I test on my machine (mac os x 10.10 ) and was not able to reproduce.  You
may need to go to the issue on the Apache Flex site and either open a new
issue or update this one:

https://issues.apache.org/jira/browse/FLEX-34851

I would include a copy of the installer.log and installer.xml files for the
people on the Apache Flex team to look at.  They are usually really quick
to respond.

**Comment by modecolems** [comment]
Hi,

I finally try one more time this morning and it finally works.
Whatever, thanks a lot for your help.

Regards.

**Comment by iccLowe-Margareta** [comment]
Installer version 3.2.0 (mac)
Using Locale: en_GB
Fetched the SDK download mirror URL from the CGI.
SDK version Apache Flex SDK 4.14.1
AIR version 16.0
Flash Player version 16.0
Creating Apache Flex home
Creating temporary directory
Downloading Apache Flex SDK from: http://mirror.catn.com/pub/apache/flex/4.14.1/binaries/apache-flex-sdk-4.14.1-bin.tar.gz
Verifying Apache Flex SDK MD5 Signature
The Apache Flex SDK MD5 Signature of the downloaded files matches the reference. The file is valid.
Unzipping: /Users/margareta.sandor/src/ApacheFlex/temp/apache-flex-sdk-4.14.1-bin.tar.gz
Finished unzipping: /Users/margareta.sandor/src/ApacheFlex/temp/apache-flex-sdk-4.14.1-bin.tar.gz
Downloading Adobe AIR Runtime Kit for Mac from: http://airdownload.adobe.com/air/mac/download/16.0//AdobeAIRSDK.tbz2
Validating download: /Users/margareta.sandor/src/ApacheFlex/in/AdobeAIRSDK.tbz2
Finished untaring: /Users/margareta.sandor/src/ApacheFlex/in/airsdk/AdobeAIRSDK.tar
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/frameworks/libs/air to /Users/margareta.sandor/src/ApacheFlex/frameworks/libs
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/frameworks/projects/air to /Users/margareta.sandor/src/ApacheFlex/frameworks/projects
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/include to /Users/margareta.sandor/src/ApacheFlex
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/lib/android to /Users/margareta.sandor/src/ApacheFlex/lib
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/lib/aot to /Users/margareta.sandor/src/ApacheFlex/lib
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/lib/nai to /Users/margareta.sandor/src/ApacheFlex/lib
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/runtimes to /Users/margareta.sandor/src/ApacheFlex
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/samples/badge to /Users/margareta.sandor/src/ApacheFlex/samples
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/samples/icons to /Users/margareta.sandor/src/ApacheFlex/samples
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/templates/air to /Users/margareta.sandor/src/ApacheFlex/templates
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/templates/extensions to /Users/margareta.sandor/src/ApacheFlex/templates
Copying files from /Users/margareta.sandor/src/ApacheFlex/in/airsdk/templates/sdk to /Users/margareta.sandor/src/ApacheFlex/templates
Installing Adobe Flash Player playerglobal.swc from: http://download.macromedia.com/get/flashplayer/updaters/16//playerglobal16_0.swc
Validating download: /Users/margareta.sandor/src/ApacheFlex/frameworks/libs/player/16.0/playerglobal.swc
Downloading 2.2.zip from: https://github.com/swfobject/swfobject/archive
Validating download: /Users/margareta.sandor/src/ApacheFlex/in/swfobject_2_2.zip
Download complete
Downloading OSMF2_0.swc?format=raw from: http://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs
      [get] [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032" errorID=2032]

**Comment by harshmer** [comment]
Hello,

I'm using the 3.2.0 installer and i'm still facing the same issue for the swfobject. the installer cant download it. Is there any way i can manually get flex sdk 4.14.1 with air 19.0 and other dependencies of it?

Any updates on it?

Thank you for your reply in advance.

**Comment by mcannon77** [comment]
Having the same problem trying to get 4.11.0.  Is this the only way to get these SDK's now?

**Comment by pipwerks** [comment]
SWFObject is not responsible for the Flex installer, closing as this is outside the scope of SWFObject and not something the SWFObject team controls.

Also please note SWFObject is no longer in active development.
